### ISSUE TITLE
App not connecting with Anki car

### ISSUE THREAD

**Issue by echoGee** [gravesjohnr/AnkiNodeDrive#3]
I'm trying to run the server.js file to connect to a SKULL car. However, after running the server

> C:\AnkiNodeDrive>node server.js
> Example app listening at http://pi:7877
> http://pi:7877/getDevices
> http://pi:7877/connect/:carname
> http://pi:7877/setSpeed/:carname/:speedValue
> http://pi:7877/setLights/:carname/:lightValue

I see that the server address is http://pi:7877/getDevices , which is confusing. So I tried to get both 

> http://pi:7877/getDevices and
> http://localhost:7877/getDevices

The http://localhost:7877/getDevices connected to the server, but is returning an empty list , even though one car is in bluetooth range. 

> {"carList":[]}

Any ideas on how to debug this ?

**Comment by gravesjohnr** [comment]
It sounds like you are running it as a non privileged user.  I'm not 
sure how all that works under windows.  On Linux, you run it as root or 
use setcap to make the command run as root.

When the server is started, it will display what cars it sees on the 
console.


------------------------------------------------------------------------

*From:* Eohan
*Sent:* Saturday, March 25, 2017 8:17AM
*To:* Gravesjohnr/ankinodedrive
*Cc:* Subscribed
*Subject:* [gravesjohnr/AnkiNodeDrive] App not connecting with Anki car (#3)

**Comment by echoGee** [comment]
Yes.  That was the issue.
